# Adding/Removing Columns
### 01 - Adding/Removing Columns | Basics
### 02 - Renaming columns
### 03 - Adding/Removing Columns | Sting Operation, Datetime(dt.to_date) Operations
### 04 - Adding/Removing Columns | Using Lambda, Custom Function w/ .apply()

In [ ]:
import pandas as pd
import numpy as np
coffee = pd.read_csv("./warmup-data/coffee.csv")
coffee_new = coffee.copy()
coffee_new['price'] = 4.99
coffee_new['new_price'] = np.where(coffee_new['Coffee Type'] == 'Espresso', 3.99, 5.99)
coffee_new.head()

### 01 - Adding/Removing Columns | Basics

In [ ]:
coffee_new.drop(columns=['price'], inplace=True)   #if we wanna modify the table, inplace=True is needed
coffee_new

In [ ]:
coffee_new['revenue'] = coffee_new['Units Sold']*coffee_new['new_price']
coffee_new.head()

### 02 - Renaming Columns

In [ ]:
coffee_new.rename(columns={'new_price':'price', 'Day':'day'})

### 03 - Adding/Removing Columns | Sting Operation

In [ ]:
bios = pd.read_csv("./data/bios.csv")
bios_new = bios.copy()
bios_new.head()

In [ ]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]
bios_new

In [ ]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], format="%Y-%m-%d")
bios_new

In [ ]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

bios_new[["name", "born_year"]]

### 04 - Adding/Removing Columns | Using Lambda, Custom Function w/ .apply()

In [54]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Short' if x<165 else ('Average' if x < 185 else 'Tall')  )
bios_new.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date     first_name born_datetime  born_year height_category  
0  1960-10-02  Jean-François    1886-12-12     1886.0            Tall  
1         NaN         Arnaud    1969-04-01     1969.0         Average  
2  1994-07-17           Jean    1898-08-13     1898.0         Average  
3  1978-03-20        Jacques    1895-05-11     1895.0         Average  
4  1930-07-25         Albert    1878-04-17     1878.0            Tall

In [55]:
def categorize_athlet(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'LightWeight'
    elif row['height_cm'] < 185 or row['weight_kg'] <=80:
        return "MiddleWeight"
    else:
        return "HeavyWeight"
    
bios_new['weight_category'] = bios_new.apply(categorize_athlet, axis=1)
bios_new.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date     first_name born_datetime  born_year height_category  \
0  1960-10-02  Jean-François    1886-12-12     1886.0            Tall   
1         NaN         Arnaud    1969-04-01     1969.0         Average   
2  1994-07-17           Jean    1898-08-13     1898.0         Average   
3  1978-03-20        Jacques    1895-05-11     1895.0         Average   
4  1930-07-25         Albert    1878-04-17     1878.0            Tall   

  weight_category  
0     HeavyWeight  
1    MiddleWeight  
2    MiddleWeight  
3     LightWeight  
4     HeavyWeight

In [58]:
import numpy as np
test = np.array([[1,2,3],[4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
avg_row = test.mean(axis=1)
avg_row

array([2., 5.])

In [62]:
avg_col = test.mean(axis=0)
avg_col

array([2.5, 3.5, 4.5])